sudo: required

language: go

go:
  - 1.11.x

env:
  - GO111MODULE=on

before_install:
  - go test -v

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build --no-cache -t aracki/fus:$TRAVIS_COMMIT .
  - docker push aracki/fus

