FROM golang:1.10 as builder
WORKDIR /go/src/github.com/Aracki/
RUN git clone https://github.com/Aracki/fus.git
WORKDIR /go/src/github.com/Aracki/fus
RUN go get -v
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags '-X main.VERSION=docker' -o gohttpserver

FROM debian:stretch

ARG USERNAME
ARG PASSWORD
ENV USERNAME=$USERNAME \
    PASSWORD=$PASSWORD

RUN apt-get update && apt-get install -y ca-certificates
RUN useradd -d /data -m -u 1000 -U upload
USER upload
VOLUME /data
WORKDIR /app
COPY --from=builder /go/src/github.com/Aracki/fus .
EXPOSE 8000
ENTRYPOINT /app/gohttpserver --root=/data --upload --delete --auth-type http --auth-http $USERNAME:$PASSWORD

